build at Thu 21 Sep 15:13:54 BST 2023

diff --git a/logstat b/logstat
--- a/logstat
+++ b/logstat
@@ -2,12 +2,12 @@
 
 ## ggtool logstat
 
-regex='\bopsview\.[a-z]*'
+regex='\bopsview\.[a-z]*' # Default regex - selects Opsview components
 
 while [[ $# > 0 ]]; do
   case "${1,,}" in
-    -r | --regex ) shift; regex="$1" ;;
-    -t | --time  )
+    -r | --regex   ) shift; regex="$1" ;;
+    -t | --time    )
       case "${2,,}" in
         d | day ) shift; regex="^[A-Z][a-z]{2} +[0-9]+" ;;
         h | hour) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}" ;;
@@ -32,18 +32,30 @@ else
 fi
 
 {
-  echo -e "\e[1mGrouping,Error,Warning,Total\e[0m"
+  echo -e "\e[1G\e[1mGrouping,Error,Warning,Info,Debug,Other,Total\e[0m"
   IFS=$'\n'
-  for match in $(cat $tempfile | grep -Eo "$regex" | sort | uniq); do
+  matches=$(cat $tempfile | grep -Eo "$regex" | sort | uniq)
+    for dot in $matches; do
+    echo -n "_" >&2
+  done
+  echo -en "\e[1G" >&2
+    for match in $matches; do
+    echo -n '.' >&2
     tot=$(cat $tempfile | grep -c "$match")
     err=$(cat $tempfile | grep "$match" | grep -Ec '\[(ERR|ERROR)\]' )
     warn=$(cat $tempfile | grep "$match" | grep -Ec '\[(WARN|WARNING)\]' )
-    echo -e "$match,\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,\e[1m$tot\e[0m"
+    info=$(cat $tempfile | grep "$match" | grep -Ec '\[(INFO|NOTICE)\]' )
+    debug=$(cat $tempfile | grep "$match" | grep -Ec '\[DEBUG\]' )
+    other=$(cat $tempfile | grep "$match" | grep -Evc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
+    echo -e "$match,\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,$info,\e[34m$debug\e[0m,\e[2m$other\e[0m,\e[1m$tot\e[0m"
   done
-  tot=$(cat $tempfile | grep -Evc "$regex")
-  err=$(cat $tempfile | grep -Ev "$regex" | grep -Ec '\[(ERR|ERROR)\]' )
-  warn=$(cat $tempfile | grep -Ev "$regex" | grep -Ec '\[(WARN|WARNING)\]' )
-  echo -e "(Other),\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,\e[1m$tot\e[0m"
-} | column -s, -t -R 2,3,4
+  tot=$(cat $tempfile | grep -Ec "$regex")
+  err=$(cat $tempfile | grep "$regex" | grep -Ec '\[(ERR|ERROR)\]' )
+  warn=$(cat $tempfile | grep "$regex" | grep -Ec '\[(WARN|WARNING)\]' )
+  info=$(cat $tempfile | grep "$regex" | grep -Ec '\[(INFO|NOTICE)\]' )
+  debug=$(cat $tempfile | grep "$regex" | grep -Ec '\[DEBUG\]' )
+  other=$(cat $tempfile | grep "$regex" | grep -Evc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
+  echo -e "(Other),\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,$info,\e[34m$debug\e[0m,\e[2m$other\e[0m,\e[1m$tot\e[0m"
+} | column -s, -t -R 2,3,4,5,6,7
 
 rm -f $tempfile
